sudo: false

services:
  - docker

language: python

python:
  - 3.5

before_install:
  - docker pull iron/functions
  - docker run -id --privileged --env API_URL=http://0.0.0.0:8080/v1 -p 0.0.0.0:9999:8080 iron/functions

env:
  - TOX_ENV="py35"
  - TOX_ENV="pep8"
  - TOX_ENV="docs"

install:
  - pip install tox==2.5.0
  - pip install codecov

script:
  - FUNCTIONS_API_URL=http://localhost:9999/v1 tox -e $TOX_ENV

after_success:
  - codecov
